### ISSUE TITLE
Breaks with taskwarrior 2.4.0

### ISSUE THREAD

**Issue by dgrabla** [svenhertle/tasktime#3]
*[feature/newUserProfileCurrency] 57%
Traceback (most recent call last):
  File "/home/dgrabla/bin/tasktime.py", line 215, in <module>
    c.create_statistic(project)
  File "/home/dgrabla/bin/tasktime.py", line 53, in create_statistic
    tasks = json.loads(json_str)
  File "/usr/lib/python3.2/json/__init__.py", line 309, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.2/json/decoder.py", line 353, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.2/json/decoder.py", line 369, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 2 column 1 (char 331)

**Comment by fmeynadier** [comment]
I have just proposed a fix for that, see https://github.com/svenhertle/tasktime/pull/4/files

**Comment by dgrabla** [comment]
Hi, I tested the changes. This fixes my issue with taskwarrior 2.4. Kindly @svenhertle pull the changes. Thanks @fmeynadier for not being as lazy as me :-)
