### ISSUE TITLE
Projects with tasks created pre-taskwarrior 2.4 crash tasktime

### ISSUE THREAD

**Issue by dgrabla** [svenhertle/tasktime#5]
If the project is old and has mixed tasks (2.4 and >2.4) 

```
[~]> tasktime.py PROJECT                                   
Configuration override rc.json.array:on
Project: PROJECT

test2 ...
    Duration: 00:00:03
test ...
    Duration: 00:00:02
Traceback (most recent call last):
  File "/home/dgrabla/bin/tasktime.py", line 219, in <module>
    c.create_statistic(project)
  File "/home/dgrabla/bin/tasktime.py", line 61, in create_statistic
    time = self.handle_tasks(tasks)
  File "/home/dgrabla/bin/tasktime.py", line 67, in handle_tasks
    tmp_seconds = self.get_task_time(t)
  File "/home/dgrabla/bin/tasktime.py", line 85, in get_task_time
    seconds += self.calc_time_delta(last_start, a["entry"])
  File "/home/dgrabla/bin/tasktime.py", line 93, in calc_time_delta
    delta = stop_time - start_time
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
```

**Comment by fmeynadier** [comment]
Hi,

I don't think the problem is with mixing pre2.4 with 2.4 tasks : that's what I do, and I can't reproduce the bug.

Seems to me you have a "stop" that doesn't match a "start" (or vice-versa). You could try to edit the task and check/correct the succession of annotations.

**Comment by dgrabla** [comment]
You are totally right, the error appeared because I messed up the dates
