### ISSUE TITLE
str() takes at most 1 argument (2 given)

### ISSUE THREAD

**Issue by echo-bravo-yahoo** [svenhertle/tasktime#6]
$ tasktime.py personal

Configuration override rc.json.array:on
Traceback (most recent call last):
  File "tasktime.py", line 219, in <module>
    c.create_statistic(project)
  File "tasktime.py", line 54, in create_statistic
    json_str=str(json_tmp, encoding="utf8")
TypeError: str() takes at most 1 argument (2 given)

**Comment by echo-bravo-yahoo** [comment]
$ python --version
Python 2.7.13
$ task --version
2.5.1
